/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Chunk_ExtractQPSK.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(66eb4054dfd4291fdb1fab7495aa689a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Chunk_ExtractQPSK.h>
// pydoc.h is automatically generated in the build directory
#include <Chunk_ExtractQPSK_pydoc.h>

void bind_Chunk_ExtractQPSK(py::module& m)
{

    using Chunk_ExtractQPSK    = gr::HighDataRate_Modem::Chunk_ExtractQPSK;


    py::class_<Chunk_ExtractQPSK, gr::block, gr::basic_block,
        std::shared_ptr<Chunk_ExtractQPSK>>(m, "Chunk_ExtractQPSK", D(Chunk_ExtractQPSK))

        .def(py::init(&Chunk_ExtractQPSK::make),
           D(Chunk_ExtractQPSK,make)
        )
        



        ;




}








