/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Chunk_ExtractBPSK.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f787b5e71620758fd87d2d3e4965965c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Chunk_ExtractBPSK.h>
// pydoc.h is automatically generated in the build directory
#include <Chunk_ExtractBPSK_pydoc.h>

void bind_Chunk_ExtractBPSK(py::module& m)
{

    using Chunk_ExtractBPSK    = gr::HighDataRate_Modem::Chunk_ExtractBPSK;


    py::class_<Chunk_ExtractBPSK, gr::block, gr::basic_block,
        std::shared_ptr<Chunk_ExtractBPSK>>(m, "Chunk_ExtractBPSK", D(Chunk_ExtractBPSK))

        .def(py::init(&Chunk_ExtractBPSK::make),
           D(Chunk_ExtractBPSK,make)
        )
        



        ;




}








