/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Decode_RS.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(90ac0d95287eb604233a7f368426a668)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Decode_RS.h>
// pydoc.h is automatically generated in the build directory
#include <Decode_RS_pydoc.h>

void bind_Decode_RS(py::module& m)
{

    using Decode_RS    = gr::HighDataRate_Modem::Decode_RS;


    py::class_<Decode_RS, gr::block, gr::basic_block,
        std::shared_ptr<Decode_RS>>(m, "Decode_RS", D(Decode_RS))

        .def(py::init(&Decode_RS::make),
           D(Decode_RS,make)
        )
        



        ;




}








