/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Encode_RS.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3300dbebb313fa7f023f02b22d1ff86e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Encode_RS.h>
// pydoc.h is automatically generated in the build directory
#include <Encode_RS_pydoc.h>

void bind_Encode_RS(py::module& m)
{

    using Encode_RS    = gr::HighDataRate_Modem::Encode_RS;


    py::class_<Encode_RS, gr::block, gr::basic_block,
        std::shared_ptr<Encode_RS>>(m, "Encode_RS", D(Encode_RS))

        .def(py::init(&Encode_RS::make),
           D(Encode_RS,make)
        )
        



        ;




}








