/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Extract_Frame.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ea7b2b03ee604c8d4071dad477ab89ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Extract_Frame.h>
// pydoc.h is automatically generated in the build directory
#include <Extract_Frame_pydoc.h>

void bind_Extract_Frame(py::module& m)
{

    using Extract_Frame    = gr::HighDataRate_Modem::Extract_Frame;


    py::class_<Extract_Frame, gr::block, gr::basic_block,
        std::shared_ptr<Extract_Frame>>(m, "Extract_Frame", D(Extract_Frame))

        .def(py::init(&Extract_Frame::make),
           D(Extract_Frame,make)
        )
        



        ;




}








