/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Frame_Extract_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9a5fb3653b537644bb71ed2ab710b6e5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Frame_Extract_ff.h>
// pydoc.h is automatically generated in the build directory
#include <Frame_Extract_ff_pydoc.h>

void bind_Frame_Extract_ff(py::module& m)
{

    using Frame_Extract_ff    = gr::HighDataRate_Modem::Frame_Extract_ff;


    py::class_<Frame_Extract_ff, gr::block, gr::basic_block,
        std::shared_ptr<Frame_Extract_ff>>(m, "Frame_Extract_ff", D(Frame_Extract_ff))

        .def(py::init(&Frame_Extract_ff::make),
           D(Frame_Extract_ff,make)
        )
        



        ;




}








