/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Resolve_Phase.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3c99babf021e613607408a6b388fefc1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Resolve_Phase.h>
// pydoc.h is automatically generated in the build directory
#include <Resolve_Phase_pydoc.h>

void bind_Resolve_Phase(py::module& m)
{

    using Resolve_Phase    = gr::HighDataRate_Modem::Resolve_Phase;


    py::class_<Resolve_Phase, gr::block, gr::basic_block,
        std::shared_ptr<Resolve_Phase>>(m, "Resolve_Phase", D(Resolve_Phase))

        .def(py::init(&Resolve_Phase::make),
           D(Resolve_Phase,make)
        )
        



        ;




}








