/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TAG_CHUNKpreamble.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2073d585087bfcf5a4113cb439b9d876)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/TAG_CHUNKpreamble.h>
// pydoc.h is automatically generated in the build directory
#include <TAG_CHUNKpreamble_pydoc.h>

void bind_TAG_CHUNKpreamble(py::module& m)
{

    using TAG_CHUNKpreamble    = gr::HighDataRate_Modem::TAG_CHUNKpreamble;


    py::class_<TAG_CHUNKpreamble, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<TAG_CHUNKpreamble>>(m, "TAG_CHUNKpreamble", D(TAG_CHUNKpreamble))

        .def(py::init(&TAG_CHUNKpreamble::make),
           D(TAG_CHUNKpreamble,make)
        )
        



        ;




}








