/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Tag_FrameASM_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7dff2700352638c14579ca4219bbc704)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Tag_FrameASM_bb.h>
// pydoc.h is automatically generated in the build directory
#include <Tag_FrameASM_bb_pydoc.h>

void bind_Tag_FrameASM_bb(py::module& m)
{

    using Tag_FrameASM_bb    = gr::HighDataRate_Modem::Tag_FrameASM_bb;


    py::class_<Tag_FrameASM_bb, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Tag_FrameASM_bb>>(m, "Tag_FrameASM_bb", D(Tag_FrameASM_bb))

        .def(py::init(&Tag_FrameASM_bb::make),
           D(Tag_FrameASM_bb,make)
        )
        



        ;




}








