/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Tag_FrameASM.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(49398a1c084848d858600e271e7cdbfe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <HighDataRate_Modem/Tag_FrameASM.h>
// pydoc.h is automatically generated in the build directory
#include <Tag_FrameASM_pydoc.h>

void bind_Tag_FrameASM(py::module& m)
{

    using Tag_FrameASM    = gr::HighDataRate_Modem::Tag_FrameASM;


    py::class_<Tag_FrameASM, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Tag_FrameASM>>(m, "Tag_FrameASM", D(Tag_FrameASM))

        .def(py::init(&Tag_FrameASM::make),
           D(Tag_FrameASM,make)
        )
        



        ;




}








