/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-HighDataRate_Modem
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_HIGHDATARATE_MODEM_API_H
#define INCLUDED_HIGHDATARATE_MODEM_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_HighDataRate_Modem_EXPORTS
#define HIGHDATARATE_MODEM_API __GR_ATTR_EXPORT
#else
#define HIGHDATARATE_MODEM_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_HIGHDATARATE_MODEM_API_H */
